/**
 * Writes docs/prompts/<dialect>.md: the paste-in prompt for each dialect, with steps for ChatGPT,
 * Claude and Gemini. The prompt works in any app, phones included, with nothing to install.
 *
 *   tsx scripts/build-prompts.ts          # write the files
 * tests/data/prompts.test.ts fails when a file is out of date (run this script to fix it).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Dictionary } from '../src/core/dictionary.js';
import { CURRENT_MEMORY_VERSION, MemorySchema } from '../src/core/memory/index.js';
import { buildPortablePrompt } from '../src/core/portable.js';
import { buildBundle } from './build-data.js';

/** Dialects with a guide and an avoid list, most widely spoken first. */
export const PROMPT_DIALECTS = ['ar-eg', 'ar-levantine', 'ar-ps', 'ar-jo', 'ar-sy', 'ar-lb', 'ar-sa', 'ar-gulf', 'ar-iq', 'ar-ma', 'ar-dz', 'ar-tn', 'ar-sd', 'ar-ps-fallahi'];

const REPO = 'https://github.com/c2do/OpenAccent';

export function promptPages(dataRoot: string): Record<string, string> {
  const dict = new Dictionary(buildBundle(dataRoot, { validate: false }));
  const memory = MemorySchema.parse({ version: CURRENT_MEMORY_VERSION });
  const pages: Record<string, string> = {};
  const index: string[] = [];
  for (const id of PROMPT_DIALECTS) {
    const d = dict.getDialect(id);
    if (!d) continue;
    const ar = d.name.ar ?? d.name.en;
    const prompt = buildPortablePrompt(dict, memory, id);
    index.push(`| [${ar}](${id}.md) | ${d.name.en} | \`${id}\` |`);
    pages[`${id}.md`] = `<!-- Generated by scripts/build-prompts.ts from data/. Do not edit by hand. -->
<div dir="rtl">

# خلّي الذكاء الاصطناعي يحكي ${ar}

انسخ النص اللي بالمربّع والصقه في إعدادات التطبيق مرة وحدة. بعدها، لما تكتبله بـ${ar} (أو تطلب منه)، بيرد عليك مثل ما بيكتبوا الناس هناك، مش بالفصحى ولا بلهجة ثانية.

</div>

\`\`\`text
${prompt}
\`\`\`

<div dir="rtl">

## وين ألصقه؟

- **ChatGPT:** الإعدادات ← التخصيص (Personalization) ← التعليمات المخصّصة، في خانة «كيف تريد أن يرد ChatGPT؟».
- **Claude:** الإعدادات ← الملف الشخصي (Profile) ← خانة «التفضيلات الشخصية».
- **Gemini:** الإعدادات ← المعلومات المحفوظة (Saved info)، أو اعمل Gem جديد والصقه في تعليماته.

القوائم بتتغيّر أحياناً من تحديث لتحديث، فإذا ما لقيت الاسم بالضبط دوّر على «تعليمات» أو «تخصيص».

## جرّبه وقلّنا

- **صار يحكي مثل أهلك؟** أو لسا بيغلط؟ [احكيلنا هون](${REPO}/issues/new?template=feedback.yml&title=${encodeURIComponent(`[${id}] `)}): كلمة وحدة غلط بتفرق.
- بتعرف كلمة أحسن؟ [اقترحها](${REPO}/issues/new?template=add-word.yml).

**حالة هالنص:** مسودة. القواعد والكلمات كتبها الذكاء الاصطناعي من مصادر مفتوحة، ولسا بتستنى مراجعة من حدا كبر وهو بيحكي ${ar}. إذا إنت منهم، [ساعدنا نراجعها](${REPO}/issues/new?template=reviewer.yml).

</div>

---

Paste-in prompt for **${d.name.en}** (\`${id}\`) from [OpenAccent](${REPO}). Data: CC BY-SA 4.0, see [data/sources.yaml](../../data/sources.yaml). Regenerate with \`npx tsx scripts/build-prompts.ts\`.
`;
  }
  pages['README.md'] = `<!-- Generated by scripts/build-prompts.ts from data/. Do not edit by hand. -->
<div dir="rtl">

# نصوص جاهزة لكل لهجة

اختار لهجتك، انسخ النص، والصقه في إعدادات ChatGPT أو Claude أو Gemini. ما في إشي تنزّله، وبيشتغل على الموبايل.

</div>

| اللهجة | Dialect | ID |
|---|---|---|
${index.join('\n')}
`;
  return pages;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const out = join(process.cwd(), 'docs/prompts');
  mkdirSync(out, { recursive: true });
  const pages = promptPages(join(process.cwd(), 'data'));
  for (const [file, text] of Object.entries(pages)) writeFileSync(join(out, file), text);
  console.log(`✓ Wrote ${Object.keys(pages).length} files to docs/prompts/`);
}
